spring:
  application:
    name: tukuntech-ms-iam

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:2}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:600000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs    # --> Real: http://localhost:8082/api/v1/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html   # --> Real: http://localhost:8082/api/v1/swagger-ui.html

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: tukuntech-api
      access-token-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
      refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
      maximum-sessions: ${JWT_MAX_SESSIONS:5}

  seed:
    enabled: ${APP_SEED_ENABLED:false}
    admin:
      email: ${SEED_ADMIN_EMAIL:admin@tukuntech.com}
      password: ${SEED_ADMIN_PASSWORD:Admin123}
    attendant:
      email: ${SEED_ATTENDANT_EMAIL:attendant@tukuntech.com}
      password: ${SEED_ATTENDANT_PASSWORD:Attendant123}
    patient:
      email: ${SEED_PATIENT_EMAIL:patient@tukuntech.com}
      password: ${SEED_PATIENT_PASSWORD:Patient123}

cors:
  allowed-origins:
    - http://localhost:4200
    - http://localhost:8081
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

