spring:
  application:
    name: tukuntech-ms-iam

  cloud:
    compatibility-verifier:
      enabled: false

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}

  seed:
    admin:
      password: ${SEED_ADMIN_PASSWORD}
    attendant:
      password: ${SEED_ATTENDANT_PASSWORD}
    patient:
      password: ${SEED_PATIENT_PASSWORD}
